# Начало
# 2 строка 1 комментария
line_1 = "try_to_write_a_line"
num_1 = 1.0
num_2 = 20
perem_1 = true

# словарь
[dict]
num_from_dict = 15
perem_from_dict = false

# комментарий в середине
# 2 строка комментария в середине

num_3 = 50
# прибавим 10 к num_3 и сохраним в новую переменную res
res = "!(+ num_3 10)"

# умножим num_3 на 2 и сохраним в ту же переменную num_3
num_3 = "!(* num_3 2)"
# вычтем из num_3 3 и сохраним результат в новую переменную vers
vers = "!(- num_3 3)"

# отрицательное число
minus = -1
# пересохраним в ту же переменную модуль числа из minus
minus = "!(abs minus)"

# комментарий в конце